### PR TITLE
Mark headings in XLIFFs so that ATE can indicate that these fields have SEO significance

### PR DESCRIPTION
**Pull request by kagg-design**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmltm-3081

### CODE REVIEW

**Comment by kagg-design** [comment]
Testers: This is PR with the same content as https://github.com/OnTheGoSystems/wpml-page-builders-cornerstone/pull/5. I have opened this one to be consistent with branch name.

Anyway, phpunit test fails, as it expects my changes in page-builders repo, made in https://github.com/OnTheGoSystems/wpml-page-builders/pull/63

**Review by strategio — DISMISSED** [review]
+1 @kagg-design

**Comment by strategio** [comment]
You have one test failing @kagg-design.

**Comment by kagg-design** [comment]
> You have one test failing @kagg-design.

As I wrote above for testers, it is a kind of problem with branches. My changes in Page Builders are not available here, despite branches have similar names.

**Pull request merged**
