### PR TITLE
Add support for Card element

### PR DESCRIPTION
**Pull request by izzi-hassan**
Added nodes for the 'Card' element's text and anchor fields.

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7232

### CODE REVIEW

**Review by dgwatkins — CHANGES_REQUESTED** [review]
@izzi-hassan Are you able to add this to unit tests?

**Comment by izzi-hassan** [comment]
@dgwatkins I spoke with Pierre yesterday and he suggested we didn't need a test for this kind of change. I'll ping you on MM for some guidance.

**Comment by strategio** [comment]
Yes, I believe testing a configuration with unit test does not make sense. There is no logic to test so we just end up copying the config in the test (this is really useless).

As the main array of configuration is already covered with one test, adding some elements in the config will not impact the coverage level.

What we need for this kind of change is to extend our CC tests.

However, I can see that tests are failing so we still have something wrong. I'll check this!

**Review by dgwatkins — DISMISSED** [review]

**Comment by strategio** [comment]
I added on commit to move the configuration array to a static method.

Testing an array does not make sense to me, there's no logic in it. The only thing we were testing is our "copy/paste" ability.

The changes we are making in this configuration files should be tested in CC tests.

+1 @izzi-hassan BTW.

**Review by strategio — DISMISSED** [review]

**Comment by strategio** [comment]
@izzi-hassan, just one more little thing, please always add a link to the YT ticket in your commit message (See how I fixed it in your commit). And also paste the link to the PR in the YT ticket (in the related field). That way we can always jump from one to the other and it helps to investigate issues.

**Review by strategio — DISMISSED** [review]

**Comment by izzi-hassan** [comment]
@strategio thanks for correcting the commit. I'd added it to the PR :)

**Review by strategio — APPROVED** [review]

**Pull request merged**
