### PR TITLE
Add support for link in Button element

### PR DESCRIPTION
**Pull request by marceltannich**
Added link support for the already existing "button" element.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-4893

### CODE REVIEW

**Comment by strategio** [comment]
Thanks @mardroid! We have just make some changes to simplify the changes in the configuration (and avoid failing tests). This is done in https://github.com/OnTheGoSystems/wpml-page-builders-cornerstone/pull/14 (not merged yet).

Could you please re-create your branch from `hotfix/wpmlcore-7232` and add again your new config element?

**Comment by marceltannich** [comment]
Thanks, @strategio, The branch hotfix/wpmlcore-7232 was already merged today. Should I re-create now from 'develop' branch?

**Comment by strategio** [comment]
@mardroid, that's right, our QA team was too fast :)

I suggest to rebuild you branch from `master` and cherry-pick your commit. Please run the following commands:
```
// Take a backup of your initial branch and delete it
git checkout hotfix/wpmlsupp-7793
git branch hotfix/wpmlsupp-7793-bk
git branch -D hotfix/wpmlsupp-7793

// Update your local repo from the OTGS one
git remote otgs git@github.com:OnTheGoSystems/wpml-page-builders-cornerstone.git
git checkout master
git pull otgs master
git reset --hard otgs/master

// Re-create your branch with your commit and push it
git branch hotfix/wpmlsupp-7793
git cherry-pick 8090184ba1fa82f4160879de131661a00a681a68
git push origin hotfix/wpmlsupp-7793 --force-with-lease
```

Once you did this, please also change the target branch to `master` in this PR.

Ping me if you are stuck.

Thanks for you contribution :)

**Comment by strategio** [comment]
Thanks @mardroid, I will close this PR and we'll use your fix in https://github.com/OnTheGoSystems/wpml-page-builders-cornerstone/pull/16.

**Pull request closed without merging**
